version: "3"

volumes:
  postgresql-data:

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    tty: true
    stdin_open: true
    volumes:
      - .:/rails-docker
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: rails-docker-db
    image: postgres:12
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
